### ISSUE TITLE
Add param to disable email notifications on Dataset export

### ISSUE THREAD

**Issue by PolinaBevad** [solvebio/solvebio-python#327]
Hi SolveBio!

Can you add the param like `email_disabled` in exporting datasets, please? 
So something similar to: 
`dataset.download('/path', email_disabled=True)`

At the moment I want to export some datasets to files automatically, so there will be a lot of spam. And this is useful when you are debugging something.

**Comment by nikolamaric** [comment]
Hi Polina,

I would like to inform you that we have resolved the issue. We added `send_email_on_completion` param to `export()` method which enables/disables sending an email when the export is ready. The default value is set to `False`.

Please find the upgraded docs regarding the issue here:

https://solvebio.github.io/solvebio-docs/reference/datasets/dataset_exports/#dataset-exports
https://solvebio.github.io/solvebio-docs/datasets/exporting/#export-a-dataset
